name: Build

# FIXME: remove testing_gq from below

on:
  push:
    branches: [ main, testing_gq ]
  pull_request:
    branches: [ main, testing_gq ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # 7.6 is not yet supported properly. Once fixed, this can be set to true
      matrix:
        include:
          # default version is set in the justfile. If setup is blank, will use default
          - type: latest
          # - setup: varnish77  -- this is current latest
          - setup: varnish76
    env:
      RUST_BACKTRACE: 1
      RUSTDOCFLAGS: -D warnings
      RUSTFLAGS: -D warnings
    steps:
      - uses: taiki-e/install-action@v2
        with: { tool: just }
      - uses: actions/checkout@v4
      - if: github.event_name == 'release'
        name: Ensure this crate has not yet been published (on release)
        run: just check-if-published
      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.setup }}-${{ matrix.latest }}
      - run: just install-varnish ${{ matrix.setup }}
      - run: just -v ci-test
